### ISSUE TITLE
can't run packetdump example with rust version 1.9 Linux

### ISSUE THREAD

**Issue by BenKnigge** [libpnet/libpnet#196]
> cargo run --example packetdump
     Running `target/debug/examples/packetdump`
thread '<main>' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:326
note: Run with `RUST_BACKTRACE=1` for a backtrace.
error: Process didn't exit successfully: `target/debug/examples/packetdump` (exit code: 101)

**Comment by mrmonday** [comment]
There are two things you need for the packetdump example to work:
 * The example needs to be run as root (or you can set the relevant permissions on the binary - I won't get into this now)
 * You need to pass the name of the interface to use.

Perhaps the example should use `expect()` rather than unwrap - [you're not the first person to have had an issue with this](https://github.com/libpnet/libpnet/issues/166).
