### ISSUE TITLE
TcpPacket numerical field getters don't have the byte order specified in documentation

### ISSUE THREAD

**Issue by SalmonProject** [libpnet/libpnet#259]
The documentation shows these getters having return types of `u32be` and `u16be`, but to check if a packet's destination port is not 443, `if tcp_pkt.get_destination() != 443` works while `tcp_pkt.get_destination().to_be() != 443` does not. (And yes, this is on a little endian machine :smile: )

**Comment by mrmonday** [comment]
Hi - this works as expected.

`libpnet` is designed so that you never need to worry about endianness. All values returned from `get_` methods, and all values passed to `set_` methods are in host endian format - you write code as if endianness does not exist, and it will just work.

The types denote what format values will be on the wire. That is, `u32be` means "this field is a u32, which should be transmitted across the network in big endian format".

I hope this clears things up for you!

**Comment by SalmonProject** [comment]
Thanks, that explains it! That is a nice, convenient design. It would really help to have that documented. Right now, I can't find it mentioned anywhere in the documentation. When I look at https://octarineparrot.com/assets/libpnet/doc/pnet/packet/tcp/struct.TcpPacket.html, the 'be' makes me not even wonder about the byte order: it sounds like it will return network order regardless of the machine's endianness.

Could you maybe explain it in the package-level documentation, and all individual struct pages where it applies?

**Comment by mrmonday** [comment]
If you have the time and motivation, it would be great if you could make the modifications and open a pull request - you're probably more qualified to fill in the gaps than I am, since you experience the issue first hand.

Documentation improvements are always welcome :)

**Comment by SalmonProject** [comment]
I'd be happy to! I'll get to it soon-ish.
