### ISSUE TITLE
OpenBSD support

### ISSUE THREAD

**Issue by kpcyrd** [libpnet/libpnet#312]
pnet_datalink currently fails to compile on openbsd. It seems there are some target_os specific filters that would need adjustment.

**Comment by mrmonday** [comment]
I've just installed OpenBSD locally and made the changes it needs to build. I'll try and run the test suite then get some fixes pushed up.

**Comment by mrmonday** [comment]
![image](https://user-images.githubusercontent.com/165689/37052387-10984586-2171-11e8-9324-a9351c9696af.png)

**Comment by kpcyrd** [comment]
@mrmonday awesome! :) Please let me know when you publish anything so I can help out with testing.

**Comment by mrmonday** [comment]
I've opened a PR here - https://github.com/libpnet/libpnet/pull/313 I'll merge it in once CI passes so I know I haven't broken the other platforms.

I've tested on OpenBSD 6.2, it should work on any older version you might be using though (the parts of the system libpnet relies on haven't really changed since the 90s).

I've only tested on amd64 - it would be great if you could test with a 32 bit system.

**Comment by mrmonday** [comment]
OpenBSD support is now published on crates.io in v0.21.0 - https://crates.io/crates/pnet/0.21.0

**Comment by kpcyrd** [comment]
@mrmonday awesome, thanks a lot!
