### ISSUE TITLE
depends on orphaned syntex crate.

### ISSUE THREAD

**Issue by rbtcollins** [libpnet/libpnet#355]
The subject says it all.

**Comment by ignatenkobrain** [comment]
@JuxhinDB any news here? We can't package pnet stuff for Fedora due to this.

**Comment by JuxhinDB** [comment]
Hi, apologies for the delay in replying. Took a look at the issue and it seems that we're using an unmaintained crate.

The alternatives from what it seems is to make use of [quote](https://crates.io/crates/quote) and [https://crates.io/crates/syn](https://crates.io/crates/syn) crates potentially to achieve the same thing. 

I'm still getting my way around the codebase but there are quite a few places were we heavily use this:

https://github.com/libpnet/libpnet/blob/9365db496216b51562977bd4eafdb98c773bae95/pnet_macros/src/lib.rs#L146-L157

I'd look into it, but it would need to be towards beginning of June. If you wish, you are more than welcome to open a PR for this and we can work on it.

**Comment by chifflier** [comment]
Hi,
I have worked on a rewrite of the `proc_macro` crate, removing all `syntex` dependencies, and using only `syn`, `quote` and `proc_macro`. It basically works (test suite passes, and the good news is it does not require many changes in code using `[packet]`), but it needs some polishing (some things changed, for ex in the way errors are returned) and tests. I intend to submit a PR after some cleanups.
Are you interested in such PR? if yes, you can assign the issue to me.

**Comment by mrmonday** [comment]
Definitely interested, I look forward to seeing what you have come up with :)

**Comment by chifflier** [comment]
Hi,
Most of the work has been done. I'm still running some tests (checking my crates using pnet), but you can see the in-progress work here: https://github.com/libpnet/libpnet/compare/master...chifflier:dev/migrate-to-proc-macro-v0.1

Some notes:
- syntex dependency is completely removed, as well as requirements for `build.rs` and compiler plugins
- I implemented a custom derive `#[derive|(Packet)]`, and for backwards compatibility I added a custom struct attribute `#[packet]`
- for `pnet_packet` calling crates, this is completely transparent, no code has to change
- the `pnet_macros` test suite passes, I also added more tests for `construct_with`, `payload` and `length_fn`
- the patch ends up being quite big. This is mostly due to moving all `<file>.rs.in` to `<file>.rs` in `pnet_packet`. If you really want to avoid that, 89cf5f27b7faac39f81cf355a8ed11176900009b can be dropped

There are 2 things where I could use your help:
- in a proc_macro, env vars from cargo are not available, so I had to replace the uses of `CARGO_CFG_TARGET_ENDIAN`. I used `cfg!(target_endian = "little")`, but I'm not entirely sure this is correct
- the CI is failiing (see https://travis-ci.org/github/chifflier/libpnet), but I'm not sure how to solve it. `compiletest_rs` is failing, and complains `Problem with env var 'DYLD_LIBRARY_PATH': NotPresent'`

**Comment by mrmonday** [comment]
* The CI failure appears to be this issue: https://github.com/Manishearth/compiletest-rs/issues/179
 * I think using `cfg!` for the endianess check is correct - I'm not sure why we weren't already using it.
 * I would be ok with `#[packet]` being removed completely and only supporting the `#[derive()]` version - I don't think too many people are using their own packet types, and for those that are there's other work they need to do anyway.
   - It would be good if you could update [docs/using_packet.md](https://github.com/libpnet/libpnet/blob/2ad90983ddc10e985392872c6ffd1e3fef7ce2d5/docs/using_packet.md) with new instructions, and include a section on how to migrate
 * You can probably make the diff smaller if you break that commit in two - one to `git rm` the `.rs` file, then another to `git mv` the `.rs.in` to `.rs`.

I've had a quick scroll through your changes and they look good - I'll save a proper review for the PR.

Thanks for working on this!
