### ISSUE TITLE
Automated CI/CD Builds Failing Due to Dependent Crates Adding "Edition" Flag

### ISSUE THREAD

**Issue by mattlknight** [libpnet/libpnet#417]
Hey team,

I had some rare free time this morning, so I decided to help investigate the Travis and AppVeyor issues. Here are my current findings, please feel free to correct me if I have made a mistake. @mrmonday  @JuxhinDB.

AppVeyor Sep 16th 2019, first crate 'ipnetwork' failure, Pull request #383 - Update ipnetwork requirement from 0.14.0 to 0.15.0, Cargo.toml depends on ipnetwork = "0.14.0", was bumped to "0.15.0", which added the edition flag.

AppVeyor, Jan 4 2020, first crate 'time' failure, Pull request #395, Cargo.toml dev-depends on time = ">=0.1", on this date, time bumped to "v0.2.1", which added the edition flag.

Rust 1.27.1 and Cargo 1.27.0 are currently hard coded for appveyor, these do not support feature flag of edition. Recommend bumping rust version to latest stable, or down-revving all dependent crates that added edition flags. This should also fix PR #416 .

I'm still looking into Travis as this appears to be a very different build process than windows.

**Comment by mattlknight** [comment]
P.S. - I'm leaving my job next week, and don't have one currently lined up, so I plan on hopefully helping out more in the coming weeks.

**Comment by pheki** [comment]
Looks like the build error on linux is: 
```
error[E0425]: cannot find function `precise_time_ns` in crate `time`

  --> benches/rs_receiver.rs:36:27

   |

36 |     timestamps.push(time::precise_time_ns() / 1_000);

   |                           ^^^^^^^^^^^^^^^ not found in `time`

error[E0425]: cannot find function `precise_time_ns` in crate `time`

  --> benches/rs_receiver.rs:43:43

   |

43 |                     timestamps.push(time::precise_time_ns() / 1_000);

   |                                           ^^^^^^^^^^^^^^^ not found in `time`

error: aborting due to 2 previous errors
```
Which is probably due to this bug in time 2.9: https://github.com/time-rs/time/issues/237, fixed by https://github.com/time-rs/time/commit/dcf41908e4d9f787142953c1fbcfe9750360637b (which has not been released yet).

Also, doesn't it make sense to enable windows build in travis? It has been available since October 2011.

**Comment by patVog** [comment]
@pheki IMHO it is due to integration of time crate into std. See: https://stackoverflow.com/questions/55583503/is-stdtimeduration-as-precise-as-timeprecise-time-ns-from-time-crate

I think I have a working solution for this but I cannot verify it since I do not really know how to run the benchmark tests. If I do `cargo bench` it runs the 'regular' tests (with some failing <- I need to investigate this further) but I cannot see the benchmarks to be executed. 
Could anyone tell me how to do this? So I can verify it.

**Comment by kishiguro** [comment]
It seems `precise_time_ns` error was fixed in travis build pipeline.  AppVeyor still pointing to Rust 1.27.1 and Cargo 1.27.0.  Let me try to bump up the stable version to 1.43.0.
